- hosts: [s1]
  become: yes
  tasks:
    - name: configure interfaces
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet dhcp

          auto swp1
          auto swp2
          auto swp3
          auto swp4

          auto br2
          iface br2 inet static
            bridge-ports swp1 swp2 swp3 swp4

    - name: reload interfaces
      shell: ifreload -a
      ignore_errors: yes
